export const PathRoute = {
  Home: "/",
  Login: "/login",
  Register: "/register",
  Profile: "/profile",
  Recipes: "/recipes/all",
  CreatedRecipe: "/recipes/created",
  SingleRecipe: "/recipes/:id",
  CreateRecipe: "/recipes/create",
  Archived: "/recipes/archived",
  Categories: "/recipes/categories",
  Category: "/recipes/categories/:id",
  Favorites: "/recipes/likes",
  UpdateRecipe: "/recipes/update/:id",
  NotFound: "*",
};
